# Association Rule and Apriori algorithm

In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  
# from apyori import apriori

In [3]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [4]:
data = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [32]:
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)

frequent_itemsets

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Kidney Beans, Eggs)
6       0.6                (Onion, Eggs)
7       0.6         (Kidney Beans, Milk)
8       0.6        (Kidney Beans, Onion)
9       0.6       (Kidney Beans, Yogurt)
10      0.6  (Kidney Beans, Onion, Eggs)

### Print the rules derived from the frequent itemsets only if the level of Confidence is above the 70 percent threshold (min_threshold=0.7)

In [11]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.00,1.00,0.00,inf
1,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.80,1.00,0.00,1.0
2,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6
3,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf
4,(Milk),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf
5,(Onion),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf
6,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf
7,"(Eggs, Onion)",(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf
8,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6
9,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf
10,(Eggs),"(Onion, Kidney Beans)",0.8,0.6,0.6,0.75,1.25,0.12,1.6
11,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,0.12,inf

### Print the rules derived from the frequent itemsets only if the level of Lift is above 1.2

In [10]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6
1,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf
2,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6
3,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf
4,(Eggs),"(Onion, Kidney Beans)",0.8,0.6,0.6,0.75,1.25,0.12,1.6
5,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,0.12,inf

### Print the rules that satisfy the following criteria:

at least 2 antecedents,
the confidence > 0.75
and lift score > 1.2

In [12]:
# Hint: you can add a new column to facilitate the calculations 
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules[rules['antecedent support']]
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.00,1.00,0.00,inf,1
1,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.80,1.00,0.00,1.0,1
2,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6,1
3,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf,1
4,(Milk),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf,1
5,(Onion),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf,1
6,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf,1
7,"(Eggs, Onion)",(Kidney Beans),0.6,1.0,0.6,1.00,1.00,0.00,inf,2
8,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6,2
9,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf,2
10,(Eggs),"(Onion, Kidney Beans)",0.8,0.6,0.6,0.75,1.25,0.12,1.6,1
11,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,0.12,inf,1

In [40]:
# Hint: you can add a new column to facilitate the calculations 
#rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))

rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf,1
1,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.600000,1
2,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf,2
3,"(Kidney Beans, Eggs)",(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.600000,2
4,(Onion),"(Kidney Beans, Eggs)",0.6,0.8,0.6,1.00,1.25,0.12,inf,1
5,(Eggs),"(Kidney Beans, Onion)",0.8,0.6,0.6,0.75,1.25,0.12,1.600000,1

In [39]:
rules[ () & () & () ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
2,"(Kidney Beans, Onion)",(Eggs),0.6,0.8,0.6,1.0,1.25,0.12,inf,2

### Print the rules derived from the frequent itemsets only if the level of Support is above the 40 percent threshold

In [42]:

frequent_itemsets

    support                                     itemsets
0       0.4                                       (Corn)
1       0.8                                       (Eggs)
2       1.0                               (Kidney Beans)
3       0.6                                       (Milk)
4       0.4                                     (Nutmeg)
5       0.6                                      (Onion)
6       0.6                                     (Yogurt)
7       0.4                         (Kidney Beans, Corn)
8       0.8                         (Kidney Beans, Eggs)
9       0.4                                 (Milk, Eggs)
10      0.4                               (Nutmeg, Eggs)
11      0.6                                (Onion, Eggs)
12      0.4                               (Yogurt, Eggs)
13      0.6                         (Kidney Beans, Milk)
14      0.4                       (Nutmeg, Kidney Beans)
15      0.6                        (Kidney Beans, Onion)
16      0.6                       (Kidney Beans, Yogurt)
17      0.4                               (Yogurt, Milk)
18      0.4                              (Nutmeg, Onion)
19      0.4                             (Nutmeg, Yogurt)
20      0.4                              (Yogurt, Onion)
21      0.4                   (Milk, Kidney Beans, Eggs)
22      0.4                 (Nutmeg, Kidney Beans, Eggs)
23      0.6                  (Kidney Beans, Onion, Eggs)
24      0.4                 (Kidney Beans, Yogurt, Eggs)
25      0.4                        (Nutmeg, Onion, Eggs)
26      0.4                       (Nutmeg, Yogurt, Eggs)
27      0.4                        (Yogurt, Onion, Eggs)
28      0.4                 (Kidney Beans, Yogurt, Milk)
29      0.4                (Nutmeg, Kidney Beans, Onion)
30      0.4               (Nutmeg, Kidney Beans, Yogurt)
31      0.4                (Yogurt, Onion, Kidney Beans)
32      0.4                      (Nutmeg, Yogurt, Onion)
33      0.4          (Nutmeg, Kidney Beans, Onion, Eggs)
34      0.4         (Nutmeg, Kidney Beans, Yogurt, Eggs)
35      0.4          (Kidney Beans, Yogurt, Onion, Eggs)
36      0.4                (Nutmeg, Yogurt, Onion, Eggs)
37      0.4        (Nutmeg, Yogurt, Onion, Kidney Beans)
38      0.4  (Nutmeg, Eggs, Kidney Beans, Yogurt, Onion)

In [47]:
rules = association_rules()
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Kidney Beans),(Corn),1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000
1,(Corn),(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf
2,(Kidney Beans),(Eggs),1.0,0.8,0.8,0.800000,1.000000,0.00,1.000000
3,(Eggs),(Kidney Beans),0.8,1.0,0.8,1.000000,1.000000,0.00,inf
4,(Milk),(Eggs),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
5,(Eggs),(Milk),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
6,(Nutmeg),(Eggs),0.4,0.8,0.4,1.000000,1.250000,0.08,inf
7,(Eggs),(Nutmeg),0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
8,(Onion),(Eggs),0.6,0.8,0.6,1.000000,1.250000,0.12,inf
9,(Eggs),(Onion),0.8,0.6,0.6,0.750000,1.250000,0.12,1.600000
10,(Yogurt),(Eggs),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
11,(Eggs),(Yogurt),0.8,0.6,0.4,0.500000,0.833333,-0.08,0.800000
12,(Kidney Beans),(Milk),1.0,0.6,0.6,0.600000,1.000000,0.00,1.000000
13,(Milk),(Kidney Beans),0.6,1.0,0.6,1.000000,1.000000,0.00,inf
14,(Nutmeg),(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf
15,(Kidney Beans),(Nutmeg),1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000
16,(Kidney Beans),(Onion),1.0,0.6,0.6,0.600000,1.000000,0.00,1.000000
17,(Onion),(Kidney Beans),0.6,1.0,0.6,1.000000,1.000000,0.00,inf
18,(Kidney Beans),(Yogurt),1.0,0.6,0.6,0.600000,1.000000,0.00,1.000000
19,(Yogurt),(Kidney Beans),0.6,1.0,0.6,1.000000,1.000000,0.00,inf
20,(Yogurt),(Milk),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
21,(Milk),(Yogurt),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
22,(Nutmeg),(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
23,(Onion),(Nutmeg),0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
24,(Nutmeg),(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
25,(Yogurt),(Nutmeg),0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
26,(Yogurt),(Onion),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
27,(Onion),(Yogurt),0.6,0.6,0.4,0.666667,1.111111,0.04,1.200000
28,"(Kidney Beans, Milk)",(Eggs),0.6,0.8,0.4,0.666667,0.833333,-0.08,0.600000
29,"(Eggs, Milk)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf
...,...,...,...,...,...,...,...,...,...
170,"(Nutmeg, Kidney Beans, Yogurt, Eggs)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
171,"(Nutmeg, Kidney Beans, Onion, Eggs)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf
172,"(Onion, Nutmeg, Yogurt, Eggs)",(Kidney Beans),0.4,1.0,0.4,1.000000,1.000000,0.00,inf
173,"(Onion, Nutmeg, Kidney Beans, Yogurt)",(Eggs),0.4,0.8,0.4,1.000000,1.250000,0.08,inf
174,"(Onion, Kidney Beans, Yogurt, Eggs)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf
175,"(Nutmeg, Kidney Beans, Eggs)","(Onion, Yogurt)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
176,"(Nutmeg, Yogurt, Eggs)","(Kidney Beans, Onion)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf
177,"(Nutmeg, Onion, Eggs)","(Kidney Beans, Yogurt)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf
178,"(Nutmeg, Kidney Beans, Yogurt)","(Onion, Eggs)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf
179,"(Nutmeg, Kidney Beans, Onion)","(Yogurt, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
180,"(Onion, Nutmeg, Yogurt)","(Kidney Beans, Eggs)",0.4,0.8,0.4,1.000000,1.250000,0.08,inf
181,"(Kidney Beans, Yogurt, Eggs)","(Nutmeg, Onion)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
182,"(Kidney Beans, Onion, Eggs)","(Nutmeg, Yogurt)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
183,"(Onion, Yogurt, Eggs)","(Nutmeg, Kidney Beans)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
184,"(Onion, Kidney Beans, Yogurt)","(Nutmeg, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
185,"(Nutmeg, Eggs)","(Onion, Kidney Beans, Yogurt)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
186,"(Nutmeg, Kidney Beans)","(Onion, Yogurt, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
187,"(Nutmeg, Yogurt)","(Kidney Beans, Onion, Eggs)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf
188,"(Nutmeg, Onion)","(Kidney Beans, Yogurt, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
189,"(Kidney Beans, Eggs)","(Onion, Nutmeg, Yogurt)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
190,"(Yogurt, Eggs)","(Nutmeg, Kidney Beans, Onion)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
191,"(Onion, Eggs)","(Nutmeg, Kidney Beans, Yogurt)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
192,"(Kidney Beans, Yogurt)","(Nutmeg, Onion, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
193,"(Kidney Beans, Onion)","(Nutmeg, Yogurt, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
194,"(Onion, Yogurt)","(Nutmeg, Kidney Beans, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
195,(Nutmeg),"(Onion, Kidney Beans, Yogurt, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf
196,(Eggs),"(Onion, Nutmeg, Kidney Beans, Yogurt)",0.8,0.4,0.4,0.500000,1.250000,0.08,1.200000
197,(Kidney Beans),"(Onion, Nutmeg, Yogurt, Eggs)",1.0,0.4,0.4,0.400000,1.000000,0.00,1.000000
198,(Yogurt),"(Nutmeg, Kidney Beans, Onion, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000
199,(Onion),"(Nutmeg, Kidney Beans, Yogurt, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.800000