In [51]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  
# from apyori import apriori

In [52]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [77]:
data = [
    ['M','O','N','K','E','Y'],
    ['D','O','N','K','E','Y'],
    ['M','A','K','E'],
    ['M','U','C','K','Y'],
    ['C','O','O','K','I','E']
]

In [76]:
# data = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
#            ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
#            ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
#            ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
#            ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [78]:
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)

frequent_itemsets

    support   itemsets
0       0.8        (E)
1       1.0        (K)
2       0.6        (M)
3       0.6        (O)
4       0.6        (Y)
5       0.8     (K, E)
6       0.6     (O, E)
7       0.6     (K, M)
8       0.6     (K, O)
9       0.6     (Y, K)
10      0.6  (K, O, E)

In [79]:
from apyori import apriori  as ap

frequent_itemset_draft = ap(data, min_support=0.6, min_confidence=0.8)  
frequent_itemset_draft = list(association_rules_by_hand)

In [80]:
for item in frequent_itemset_draft:
    print(item)
    print('\n')

RelationRecord(items=frozenset({'E'}), support=0.8, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'E'}), confidence=0.8, lift=1.0)])


RelationRecord(items=frozenset({'K'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'K'}), confidence=1.0, lift=1.0)])


RelationRecord(items=frozenset({'K', 'E'}), support=0.8, ordered_statistics=[OrderedStatistic(items_base=frozenset({'E'}), items_add=frozenset({'K'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'K'}), items_add=frozenset({'E'}), confidence=0.8, lift=1.0)])


RelationRecord(items=frozenset({'O', 'E'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset({'O'}), items_add=frozenset({'E'}), confidence=1.0, lift=1.25)])


RelationRecord(items=frozenset({'K', 'M'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset({'M'}), items_add=frozenset({'K'}), confidence=1.0, lift=1.0)])


RelationRecord(items=frozenset({'K', 'O'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset({'O'}), items_add=frozenset({'K'}), confidence=1.0, lift=1.0)])


RelationRecord(items=frozenset({'Y', 'K'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Y'}), items_add=frozenset({'K'}), confidence=1.0, lift=1.0)])


RelationRecord(items=frozenset({'K', 'O', 'E'}), support=0.6, ordered_statistics=[OrderedStatistic(items_base=frozenset({'O', 'E'}), items_add=frozenset({'K'}), confidence=1.0, lift=1.0), OrderedStatistic(items_base=frozenset({'K', 'O'}), items_add=frozenset({'E'}), confidence=1.0, lift=1.25)])

In [81]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(K),(E),1.0,0.8,0.8,0.8,1.00,0.00,1.0
1,(E),(K),0.8,1.0,0.8,1.0,1.00,0.00,inf
2,(O),(E),0.6,0.8,0.6,1.0,1.25,0.12,inf
3,(M),(K),0.6,1.0,0.6,1.0,1.00,0.00,inf
4,(O),(K),0.6,1.0,0.6,1.0,1.00,0.00,inf
5,(Y),(K),0.6,1.0,0.6,1.0,1.00,0.00,inf
6,"(K, O)",(E),0.6,0.8,0.6,1.0,1.25,0.12,inf
7,"(O, E)",(K),0.6,1.0,0.6,1.0,1.00,0.00,inf
8,(O),"(K, E)",0.6,0.8,0.6,1.0,1.25,0.12,inf

### Print the rules derived from the frequent itemsets only if the level of Lift is above 1.2

In [62]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6
1,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf
2,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6
3,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf
4,(Eggs),"(Onion, Kidney Beans)",0.8,0.6,0.6,0.75,1.25,0.12,1.6
5,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,0.12,inf

### Print the rules that satisfy the following criteria:

at least 2 antecedents,
the confidence > 0.75
and lift score > 1.2

In [65]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(Eggs),(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6,1
1,(Onion),(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf,1
2,"(Eggs, Kidney Beans)",(Onion),0.8,0.6,0.6,0.75,1.25,0.12,1.6,2
3,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.00,1.25,0.12,inf,2
4,(Eggs),"(Onion, Kidney Beans)",0.8,0.6,0.6,0.75,1.25,0.12,1.6,1
5,(Onion),"(Eggs, Kidney Beans)",0.6,0.8,0.6,1.00,1.25,0.12,inf,1

In [66]:
rules[ (rules['antecedent_len'] >= 2) &
       (rules['confidence'] > 0.75) &
       (rules['lift'] > 1.2) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
3,"(Onion, Kidney Beans)",(Eggs),0.6,0.8,0.6,1.0,1.25,0.12,inf,2

In [ ]:
01 T100 fKing’s-Crab, Sunset-Milk, Dairyland-Cheese, Best-Breadg
02 T200 fBest-Cheese, Dairyland-Milk, Goldenfarm-Apple, Tasty-Pie, Wonder-Breadg
01 T300 fWestcoast-Apple, Dairyland-Milk, Wonder-Bread, Tasty-Pieg
03 T400 fWonder-Bread, Sunset-Milk, Dairyland-Cheeseg